import { useCallback, useEffect, useState } from "react";
import { CheckCircle2, RefreshCcw } from "lucide-react";
import { deleteReport, fetchAdminReports, updateReportStatus, type ReportTicket } from "../services/api";

const steps = ["SUBMITTED", "UNDER_REVIEW", "ACKNOWLEDGED", "COMPLETED"];
const labels: Record<string, string> = { SUBMITTED: "Submitted", UNDER_REVIEW: "Under review", ACKNOWLEDGED: "Acknowledged", COMPLETED: "Completed", REJECTED: "Rejected" };
function Progress({ status }: { status: string }) { const index = status === "REJECTED" ? 0 : Math.max(0, steps.indexOf(status)); return <div className="ticket-progress">{steps.map((step, i) => <div className={`progress-step ${i <= index ? "done" : ""} ${i === index ? "current" : ""}`} key={step}><span className="progress-knot">{i < index ? <CheckCircle2 size={12} /> : i + 1}</span><small>{labels[step]}</small>{i < steps.length - 1 && <i />}</div>)}</div>; }

export default function AdminReports() {
  const [reports, setReports] = useState<ReportTicket[]>([]); const [message, setMessage] = useState(""); const [pending, setPending] = useState<{ id: number; status: string } | null>(null); const [pendingDelete, setPendingDelete] = useState<number | null>(null); const [note, setNote] = useState(""); const [busy, setBusy] = useState(false);
  const refresh = useCallback(() => void fetchAdminReports().then(setReports).catch(() => setMessage("Could not load administrative reports.")), []); useEffect(refresh, [refresh]);
  function chooseStatus(report: ReportTicket, status: string) { if (status === report.status) return; setPending({ id: report.id, status }); setNote(report.admin_note ?? ""); }
  async function confirmStatus() { if (!pending) return; setBusy(true); try { await updateReportStatus(pending.id, pending.status, note); setPending(null); setNote(""); await refresh(); } catch { setMessage("Could not update this ticket."); } finally { setBusy(false); } }
  async function confirmRemove() { if (pendingDelete === null) return; setBusy(true); try { await deleteReport(pendingDelete); setPendingDelete(null); await refresh(); } catch { setMessage("Could not remove this ticket. Confirm that you are signed in as an administrator."); } finally { setBusy(false); } }
  return <section className="dashboard-page simple-page admin-reports-page"><p className="eyebrow">Administrative response</p><h1>Flood tickets</h1><p className="muted wide-copy">Review public submissions, publish progress updates, complete valid tickets, or remove invalid reports.</p><div className="admin-report-toolbar"><b>{reports.length} tickets</b><button className="small-button" onClick={refresh}><RefreshCcw size={13} /> Refresh</button></div><div className="admin-report-list">{reports.length ? reports.map((report) => { const isPending = pending?.id === report.id; const isDeletePending = pendingDelete === report.id; return <article className="admin-report-card" key={report.id}><div className="moderation-main"><div><b>Report #{report.id}</b><small>{report.water_depth_category} · {report.road_status} · {new Date(report.observed_at).toLocaleString()}</small></div><span className={`ticket-status ${report.status.toLowerCase()}`}>{labels[report.status] ?? report.status}</span></div><Progress status={report.status} /><div className="admin-report-actions"><select value={isPending ? pending.status : report.status} onChange={(event) => chooseStatus(report, event.target.value)} disabled={busy}><option value="SUBMITTED">Submitted</option><option value="UNDER_REVIEW">Under review</option><option value="ACKNOWLEDGED">Acknowledged</option><option value="COMPLETED">Completed</option><option value="REJECTED">Rejected</option></select>{report.photo_url && <a href={report.photo_url} target="_blank" rel="noreferrer" className="ticket-photo-link">View photo</a>}{isDeletePending ? <><button className="confirm-remove-button" disabled={busy} onClick={() => void confirmRemove()}>{busy ? "Removing…" : "Confirm remove"}</button><button className="cancel-button" onClick={() => setPendingDelete(null)}>Cancel</button></> : <button className="danger-button" onClick={() => setPendingDelete(report.id)} disabled={busy}>Remove</button>}</div>{isPending && <div className="status-confirm"><label>Public update (optional)<textarea value={note} onChange={(event) => setNote(event.target.value)} rows={2} placeholder="Tell the reporter what changed…" /></label><div><button className="confirm-button" disabled={busy} onClick={() => void confirmStatus()}>{busy ? "Saving…" : "Confirm update"}</button><button className="cancel-button" onClick={() => setPending(null)}>Cancel</button></div></div>}{report.admin_note && !isPending && <div className="admin-note"><b>Public note:</b> {report.admin_note}</div>}</article>; }) : <p className="muted empty-ticket">No public tickets available.</p>}</div>{message && <p className="form-error">{message}</p>}</section>;
}
