import { useCallback, useEffect, useState } from "react";
import { Camera, CheckCircle2, MapPin, RefreshCcw, Search } from "lucide-react";
import MapView from "../components/MapView";
import { deleteReport, fetchAdminReports, fetchMyReports, searchAddress, submitFloodReport, updateReportStatus, type ReportTicket } from "../services/api";
import { useAuth } from "../store/AuthContext";
import AdminReports from "./AdminReports";

const progress = ["SUBMITTED", "UNDER_REVIEW", "ACKNOWLEDGED", "COMPLETED"];
const labels: Record<string, string> = { SUBMITTED: "Submitted", UNDER_REVIEW: "Under review", ACKNOWLEDGED: "Acknowledged", COMPLETED: "Completed", REJECTED: "Rejected" };
type AddressResult = { display_name: string; lat: string; lon: string; result_type?: string };

function ProgressLine({ status }: { status: string }) { const current = status === "REJECTED" ? 0 : Math.max(0, progress.indexOf(status)); return <div className="ticket-progress">{progress.map((step, index) => <div className={`progress-step ${index <= current ? "done" : ""} ${index === current ? "current" : ""}`} key={step}><span className="progress-knot">{index < current ? <CheckCircle2 size={12} /> : index + 1}</span><small>{labels[step]}</small>{index < progress.length - 1 && <i />}</div>)}</div>; }
function Ticket({ report }: { report: ReportTicket }) { return <article className="ticket-card"><div className="ticket-head"><div><strong>Report #{report.id}</strong><small>{new Date(report.observed_at).toLocaleString()}</small></div><span className={`ticket-status ${report.status.toLowerCase()}`}>{labels[report.status] ?? report.status}</span></div><p>{report.water_depth_category} · {report.road_status}</p><ProgressLine status={report.status} />{report.admin_note && <div className="admin-note"><b>Admin update:</b> {report.admin_note}</div>}</article>; }
function LegacyAdminReports() { const [reports, setReports] = useState<ReportTicket[]>([]); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const refresh = useCallback(() => void fetchAdminReports().then(setReports).catch(() => setMessage("Could not load administrative reports.")), []); useEffect(refresh, [refresh]); async function update(report: ReportTicket, status: string) { setBusy(true); try { const note = window.prompt("Public progress update:", report.admin_note ?? "") ?? report.admin_note ?? ""; await updateReportStatus(report.id, status, note); refresh(); } catch { setMessage("Could not update this ticket."); } finally { setBusy(false); } } async function remove(report: ReportTicket) { if (!window.confirm(`Remove report #${report.id}?`)) return; try { await deleteReport(report.id); refresh(); } catch { setMessage("Could not remove this ticket."); } } return null; }

function AddressPicker({ value, onChange, onSelect }: { value: string; onChange: (value: string) => void; onSelect: (result: AddressResult) => void }) { const [suggestions, setSuggestions] = useState<AddressResult[]>([]); const [searching, setSearching] = useState(false); useEffect(() => { if (value.trim().length < 3) { setSuggestions([]); return; } const timer = window.setTimeout(async () => { setSearching(true); try { setSuggestions(await searchAddress(value.trim())); } catch { setSuggestions([]); } finally { setSearching(false); } }, 450); return () => window.clearTimeout(timer); }, [value]); return <label className="address-field full-field">Search location<span className="address-input-wrap"><Search size={15} /><input value={value} onChange={(event) => onChange(event.target.value)} placeholder="Search a street, landmark or address" autoComplete="off" />{searching && <span className="address-searching">Searching…</span>}</span>{suggestions.length > 0 && <span className="address-suggestions">{suggestions.slice(0, 5).map((suggestion) => <button type="button" className="address-suggestion" key={`${suggestion.lat}-${suggestion.lon}`} onClick={() => { onSelect(suggestion); setSuggestions([]); }}><strong>{suggestion.display_name.split(",")[0]}</strong><small>{suggestion.result_type ?? "Map result"} · {suggestion.display_name}</small></button>)}</span>}</label>; }

export default function Reports() {
  const { user } = useAuth();
  if (user?.role === "ADMIN") return <AdminReports />;
  const [reports, setReports] = useState<ReportTicket[]>([]); const [address, setAddress] = useState(""); const [coords, setCoords] = useState<[number, number]>([80.2181, 12.9815]); const [photo, setPhoto] = useState<string | null>(null); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const refresh = useCallback(() => void fetchMyReports().then(setReports).catch(() => setMessage("Reports API unavailable. Restart the backend if it was not restarted after the ticket update.")), []); useEffect(refresh, [refresh]); const onMapClick = useCallback((point: [number, number]) => { setCoords(point); setAddress("Pinned map location"); }, []);
  function selectAddress(result: AddressResult) { setAddress(result.display_name); setCoords([Number(result.lon), Number(result.lat)]); }
  function choosePhoto(event: React.ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; if (file.size > 1_500_000) { setMessage("Choose a photo smaller than 1.5 MB."); return; } const reader = new FileReader(); reader.onload = () => setPhoto(String(reader.result)); reader.readAsDataURL(file); }
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(""); const form = new FormData(event.currentTarget); try { await submitFloodReport({ latitude: coords[1], longitude: coords[0], water_depth_category: String(form.get("depth")), road_status: String(form.get("status")), comment: String(form.get("comment") || ""), photo_url: photo, observed_at: new Date().toISOString() }); setMessage("Report submitted. Track its progress below."); setPhoto(null); setAddress(""); refresh(); (event.currentTarget as HTMLFormElement).reset(); } catch { setMessage("Could not submit the report. Please check that you are logged in."); } finally { setBusy(false); } }
  const active = reports.filter((report) => report.status !== "COMPLETED" && report.status !== "REJECTED"); const completed = reports.filter((report) => report.status === "COMPLETED");
  return <section className="dashboard-page simple-page"><p className="eyebrow">Community intelligence</p><h1>Public reports</h1><p className="muted wide-copy">Pin the exact location, attach evidence, and follow the administrative response from submission to completion.</p><div className="report-layout report-ticket-layout"><form className="form-card report-form" onSubmit={submit}><h3>Submit observation</h3><AddressPicker value={address} onChange={setAddress} onSelect={selectAddress} /><div className="report-location-banner"><MapPin size={16} /><span>Pin placed at <b>{coords[1].toFixed(5)}, {coords[0].toFixed(5)}</b><small>Choose an address, click the map, or drag the marker.</small></span></div><label>Latitude<input type="number" step="any" value={coords[1]} onChange={(event) => setCoords([coords[0], Number(event.target.value)])} required /></label><label>Longitude<input type="number" step="any" value={coords[0]} onChange={(event) => setCoords([Number(event.target.value), coords[1]])} required /></label><label>Depth<select name="depth" defaultValue="ankle"><option value="ankle">Ankle-deep</option><option value="knee">Knee-deep</option><option value="waist">Waist-deep</option><option value="impassable">Impassable</option></select></label><label>Road status<select name="status" defaultValue="slow"><option value="slow">Moving slowly</option><option value="closed">Closed</option><option value="stranded">People stranded</option></select></label><label className="full-field">Comment<textarea name="comment" rows={3} placeholder="Describe what you see…" /></label><label className="photo-upload full-field"><Camera size={15} /> {photo ? "Photo attached" : "Attach a photo"}<input type="file" accept="image/png,image/jpeg,image/webp" onChange={choosePhoto} /></label><button className="play-button" disabled={busy}>{busy ? "Submitting…" : "Submit report"}</button>{message && <p className="form-note">{message}</p>}</form><div className="report-map"><MapView routePoints={{ start: coords }} onRoutePointChange={(_, point) => { setCoords(point); setAddress("Pinned map location"); }} onMapClick={onMapClick} /></div><div className="ticket-column ticket-window"><div className="ticket-column-heading"><h3>My active tickets</h3><button className="small-button" onClick={refresh}><RefreshCcw size={13} /> Refresh</button></div>{active.length ? active.map((report) => <Ticket report={report} key={report.id} />) : <p className="muted empty-ticket">Submitted reports will appear here with their progress.</p>}<h3 className="completed-heading">Completed</h3>{completed.length ? completed.map((report) => <Ticket report={report} key={report.id} />) : <p className="muted empty-ticket">No completed reports yet.</p>}</div></div></section>;
}
